### ISSUE TITLE
Figure out how to make a visible modification to application

### ISSUE THREAD

**Issue by KingmanT** [KuraLabsCohort3-TeamEQ/Final_Project-ifmeorg#14]
Need to make a visible modification for demonstration of deployment during presentation

**Comment by Munney84** [comment]
Using the file with the color variables here: 
app/assets/stylesheets/base/_colors.scss

We can choose a color already available or add a color to the file. From there we can navigate to:
app/assets/stylesheets/dashboard/dashboard.scss

from here we can change the color of the background.

**Note this will only change the background color of the dashboard (what you see while logged in) and its contents such as "Moments", "categories", "Mood", etc. Once you click on the "About", "Blog", or other sections at the top right, the original background color will be displayed.
