### ISSUE TITLE
Create Jenkinsfile that builds app, and deploys using (future) Terraform files

### ISSUE THREAD

**Issue by KingmanT** [KuraLabsCohort3-TeamEQ/Final_Project-ifmeorg#19]

**Comment by kevinsanaycela3** [comment]
Have successfully built a Jenkins Pipeline with three stages: Plan, Init, Apply. After manually configuring an EC2 as in Deployment 4 and installing Jenkins and Terraform, the Jenkinsfile will then begin to build another EC2 with port 3000 open. The IP of this second EC2 is what is used to access the deployed application. 
I have the pipeline in a local repo here: https://github.com/kevinsanaycela3/ifme-traditional.git
